# Generated by Django 2.2.4 on 2019-08-14 15:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='唯一标识ID')),
                ('the_title', models.CharField(max_length=128, verbose_name='课题名称')),
                ('the_start_time', models.DateField(verbose_name='开题时间')),
                ('the_start_result', models.BooleanField(default=True, verbose_name='开题结果')),
                ('the_exam_count', models.IntegerField(default=0, verbose_name='论文查重次数')),
                ('the_is_delay', models.BooleanField(default=False, verbose_name='是否延期')),
                ('the_delay_reason', models.TextField(null=True, verbose_name='延期原因')),
                ('the_is_superb', models.BooleanField(default=False, verbose_name='是否优秀论文')),
                ('the_final_score', models.BooleanField(default=False, verbose_name='答辩成绩')),
            ],
            options={
                'verbose_name': '毕业论文',
                'verbose_name_plural': '毕业论文',
                'db_table': 'thesis',
                'permissions': [('can_insert_thesis', '新增毕业论文'), ('can_delete_thesis', '删除毕业论文'), ('can_update_thesis', '修改毕业论文'), ('can_search_thesis', '查询毕业论文')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ThesisOpenReport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='唯一标识ID')),
                ('time', models.DateField(default='2019', verbose_name='年份')),
                ('stu_count', models.IntegerField(default=0, verbose_name='学生数量')),
                ('schedule_count', models.IntegerField(default=0, verbose_name='按期开题人数')),
                ('delay_count', models.IntegerField(default=0, verbose_name='延期开题人数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='开题不通过人数')),
            ],
            options={
                'verbose_name': '开题报告统计',
                'verbose_name_plural': '开题报告统计',
                'db_table': 'thesis_open_report',
                'permissions': [('can_insert_thesis_open_report', '新增开题统计'), ('can_delete_thesis_open_report', '删除开题统计'), ('can_update_thesis_open_report', '修改开题统计'), ('can_search_thesis_open_report', '查询开题统计')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ThesisPlaCheck',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='唯一标识ID')),
                ('pla_date', models.DateField(verbose_name='查重时间')),
                ('pla_result', models.CharField(max_length=128, verbose_name='查重结果')),
                ('pla_rate', models.CharField(max_length=128, verbose_name='重复率')),
                ('pla_thesis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pla_thesis', to='app.Thesis', verbose_name='论文课题')),
            ],
            options={
                'verbose_name': '论文查重',
                'verbose_name_plural': '论文查重',
                'db_table': 'thesis_pla_check',
                'permissions': [('can_insert_thesis_pla_check', '新增查重结果'), ('can_delete_thesis_pla_check', '删除查重结果'), ('can_update_thesis_pla_check', '修改查重结果'), ('can_search_thesis_pla_check', '查询查重结果')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ThesisBlindReview',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='唯一标识ID')),
                ('bli_date', models.DateField(verbose_name='盲审时间')),
                ('bli_score', models.CharField(max_length=64, verbose_name='盲审结果')),
                ('bli_thesis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bli_thesis', to='app.Thesis', verbose_name='论文课题')),
            ],
            options={
                'verbose_name': '论文盲审',
                'verbose_name_plural': '论文盲审',
                'db_table': 'thesis_blind_review',
                'permissions': [('can_insert_thesis_blind_review', '新增盲审结果'), ('can_delete_thesis_blind_review', '删除盲审结果'), ('can_update_thesis_blind_review', '修改盲审结果'), ('can_search_thesis_blind_review', '查询盲审结果')],
                'default_permissions': (),
            },
        ),
    ]
